# Generated by Django 4.2.3 on 2023-08-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default_profile_picture.webp', null=True, upload_to='users/'),
        ),
    ]
