# Generated by Django 4.2.3 on 2023-08-15 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.RemoveField(
            model_name='productatribute',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productatribute',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productatribute',
            name='price',
        ),
    ]
