# Generated by Django 4.2.3 on 2023-08-17 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_product_size_remove_productatribute_color_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductAtribute',
            new_name='ProductAttribute',
        ),
    ]
